language: java


jdk:
  - openjdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle


before_install:
  - chmod +x gradlew


script:
  - make
  - ./gradlew build

#deploy:
#  provider: script
#  script: ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_KEY
#  on:
branch: master

